export const env = {
  demoMode: process.env.DEMO_MODE !== "false",
  appName: process.env.APP_NAME || "Basso Fiscal",
  sessionSecret: process.env.APP_SESSION_SECRET || "dev-session-secret-change-me",
  adminEmail: process.env.APP_ADMIN_EMAIL || "admin@basso.local",
  adminPassword: process.env.APP_ADMIN_PASSWORD || "admin123",
  workerSecret: process.env.WORKER_SECRET || "dev-worker-secret",
  cronSecret: process.env.CRON_SECRET || "dev-cron-secret",
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  storageBucket: process.env.SUPABASE_STORAGE_BUCKET || "fiscal-documents",
  ordersApiUrl: process.env.BASSO_ORDERS_API_URL || "",
  ordersApiKey: process.env.BASSO_ORDERS_API_KEY || "",
  focusEnv: process.env.FOCUS_NFE_ENV || "homologacao",
  focusToken: process.env.FOCUS_NFE_TOKEN || "",
  focusBaseUrl: process.env.FOCUS_NFE_BASE_URL || "",
  focusEmitPath: process.env.FOCUS_NFE_EMIT_PATH || "/v2/nfce",
  focusCancelPathTemplate: process.env.FOCUS_NFE_CANCEL_PATH_TEMPLATE || "/v2/nfce/{ref}",
  companySlug: process.env.COMPANY_SLUG || "la-forneria-basso",
  companyName: process.env.COMPANY_NAME || "La Forneria Basso",
  companyDocument: process.env.COMPANY_DOCUMENT || "",
  companyIe: process.env.COMPANY_IE || "",
  companyCrt: process.env.COMPANY_CRT || "",
  companyUf: process.env.COMPANY_UF || "SP",
};
